version: '3.4'

services:
  redis:
    restart: always
    container_name: tipi_redis
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis:/data

  db:
    restart: always
    container_name: tipi_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db:/data/db
      - db_data:/data/configdb
    ports:
      - "27017:27017"
    expose:
      - "27017"

  tipi_alerts:
    restart: always
    container_name: tipi_alerts
    image: tipi_alerts
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
    environment:
      PIPENV_VENV_IN_PROJECT: 1
      HOME: /app
    command: pipenv run celery -A alerts worker -l info
    depends_on:
      - redis
      - db
    user: "1000:1000"
    volumes:
      - ${APP_PATH}:/app

volumes:
  db:
    name: tipi-mongo
  db_data:
    name: tipi-mongo-data
  redis:
    name: tipi-redis
