version: '3.4'

services:
  redis:
    restart: always
    container_name: tipi_redis
    image: redis:alpine
    expose:
      - "6379"
    volumes:
      - redis:/data

  db:
    restart: always
    container_name: tipi_db
    image: mongo
    volumes:
      - db:/data/db
      - db_data:/data/configdb
    ports:
      - "27017:27017"
    expose:
      - "27017"

  tipi_tasks:
    restart: always
    container_name: tipi_tasks
    image: tipi_tasks
    build:
      context: ${APP_PATH}
      dockerfile: Dockerfile
    environment:
      PIPENV_VENV_IN_PROJECT: 1
      HOME: /app
      BROKER_URL: "redis://redis:6379/0"
    command: pipenv run celery -A tipi_tasks worker -B -l info
    depends_on:
      - redis
      - db
    user: "1000:1000"
    volumes:
      - ${APP_PATH}:/app

volumes:
  db:
    name: tipi-mongo
  db_data:
    name: tipi-mongo-data
  redis:
    name: tipi-redis
